***********
Development
***********

This chapter shows which options are available to customize the charge controller to your own needs. It
starts with creating your own EVerest modules that can be cross-compiled and run on the target, up to
creating fully customized firmware images that can be installed on the target. This chapter also
explains how to debug issues within the EVerest environment on the target.

.. include:: ../../includes/development_preparation_checklist.inc

.. include:: ../../includes/development_best_practices_everest_modules.inc
