Further Reading
===============

For more information on getting started with EVerest, including an overview of the necessary tools and
instructions on writing your own modules, please refer to the official
`EVerest documentation <https://everest.github.io/nightly>`_.

EVerest consists of multiple repositories, such as "`everest-core <https://github.com/EVerest/everest-core>`_"
and "`libocpp <https://github.com/EVerest/libocpp>`_". Each repository has its own documentation detailing its
specific role within EVerest. It should be noted that Pionix GmbH and the EVerest community maintain
all repositories that are a part of the EVerest GitHub organization. Only the EVerest modules that chargebyte
implemented and that are located in "`everest-chargebyte <https://github.com/chargebyte/everest-chargebyte>`_"
are maintained by chargebyte.

For interesting discussions and solutions to common problems, visit the EVerest community's
`Zulip <https://lfenergy.zulipchat.com/>`_ channels.

For support and issues related to the EVerest modules developed by chargebyte, please check the
:ref:`troubleshooting.rst` section of the documentation first.  If you can't find the answer, please don't
hesitate to contact chargebyte's support team (:ref:`contact`).
