.. _first_fw_update:

First Firmware Update
---------------------

When the Charge controller is manufactured, a stable software version is flashed onto it.

However, due to organizational processes and the continuous nature of software development,
this version may already be outdated.

We therefore recommend checking first, whether a software update for the Charge controller
is already available for download. If so, it should be installed immediately, as it likely
includes bug fixes and possibly new features.

Please look at section :ref:`firmware_update` for further details, e.g. where to find
the firmware update images and how to install them.
