Introduction to EVerest
=======================

EVerest is an open-source modular framework designed to create a comprehensive software stack for
electric vehicle (EV) charging.

The modular software architecture promotes flexibility and customization, allowing users to configure specific charging
scenarios using interchangeable modules. This architecture is integrated and coordinated using MQTT (Message Queuing
Telemetry Transport). EVerest aims to standardize and simplify the development of EV charging
infrastructure, making it easier for developers and companies to implement robust and scalable charging solutions.
The project includes support for various protocols like ISO 15118, OCPP, and IEC 61851, ensuring broad
compatibility and future-proofing of the charging systems.

For more information, visit the `EVerest GitHub repository <https://github.com/EVerest/EVerest>`_.
