Contact
-------

Support
^^^^^^^

EVerest is an open-source project with a lot of modules, which is supported by a big community.
chargebyte is an active part of this community. However chargebyte is not able to provide support
for every aspect of EVerest. In order to get quick answers, here are some suggestions:

Do you have general questions about EVerest, please use the EVerest community's
`Zulip <https://lfenergy.zulipchat.com/>`_.

Do you have questions about the chargebyte BSP (incl. Yocto), please use
`our support desk <https://chargebyte.com/support>`_.

Address
^^^^^^^

chargebyte GmbH

Bitterfelder Straße 1-5

04129 Leipzig

Germany

Website: `<https://chargebyte.com>`_
