name: Link check

# Allow to trigger on pull requests and manually via Github Actions
on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    # Use Ubuntu as environment
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Initialize and update submodules
      run: git submodule update --init --recursive
    # This external action cares about all the sphinx stuff
    - name: Build project
      uses: ammaraskar/sphinx-action@4.3.2
      with:
        build-command: "sphinx-build -b linkcheck source/ build/"
        docs-folder: "docs/"

